// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umxjzsboubkvwglzgwdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVteGp6c2JvdWJrdndnbHpnd2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDcwMTcsImV4cCI6MjA2NDY4MzAxN30.nZ0gHyyji7zN8yA3qCSj2Hk1JpheYib8_xtSlNdkkH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);